on:
  schedule:
    - cron: "0 0 * * *"
on: [push]
name: deploy
jobs:
  deploy:
    name: probando
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd module3_task0
      - run: make help
