name: module4_task0
on:
  schedule:
    - cron: "0 2 * * *"
  push:

  pull_request:
    types: [opened, reopened]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the Repo
        uses: actions/checkout@v3
      - working-directory: module4_task0
        run: ./setup.sh
      - name: Build the server
        working-directory: module4_task0
        run: make build
      - name: Use unit-test
        working-directory: module4_task0
        run: make unit-tests
      - name: Use integration-tests
        working-directory: module4_task0
        run: make integration-tests
