name: module3_task1
on:
  schedule:
    - cron: "2 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Repo
        uses: actions/checkout@v3
      - working-directory: module3_task1 
        run: ./setup.sh
      - working-directory: module3_task1
        run: make help
      - name: Build the server
        working-directory: module3_task1
        run: make build
      - name: Create a post
        working-directory: module3_task1
        run: make POST_NAME=welcome POST_TITLE="Welcome" post
      - working-directory: module3_task1
        run: make clean
      - working-directory: module3_task1
        run: make help
